<?php

$text['title-fail2ban']['en-us'] = "Fail2ban";
$text['title-fail2ban']['en-gb'] = "Fail2ban";
$text['title-fail2ban']['ar-eg'] = "Fail2ban";
$text['title-fail2ban']['de-at'] = "Fail2ban";
$text['title-fail2ban']['de-ch'] = "Fail2ban";
$text['title-fail2ban']['de-de'] = "Fail2ban";
$text['title-fail2ban']['el-gr'] = "Fail2ban";
$text['title-fail2ban']['es-cl'] = "Fail2ban";
$text['title-fail2ban']['es-mx'] = "Fail2ban";
$text['title-fail2ban']['fr-ca'] = "Fail2ban";
$text['title-fail2ban']['fr-fr'] = "Fail2ban";
$text['title-fail2ban']['he-il'] = "Fail2ban";
$text['title-fail2ban']['it-it'] = "Fail2ban";
$text['title-fail2ban']['nl-nl'] = "Fail2ban";
$text['title-fail2ban']['pl-pl'] = "Fail2ban";
$text['title-fail2ban']['pt-br'] = "Fail2ban";
$text['title-fail2ban']['pt-pt'] = "Fail2ban";
$text['title-fail2ban']['ro-ro'] = "Fail2ban";
$text['title-fail2ban']['ru-ru'] = "Fail2ban";
$text['title-fail2ban']['sv-se'] = "Fail2ban";
$text['title-fail2ban']['uk-ua'] = "Fail2ban";

$text['message-connection']['en-us'] = "Connection to Socket failed.";
$text['message-connection']['en-gb'] = "Connection to Socket failed.";
$text['message-connection']['ar-eg'] = "";
$text['message-connection']['de-at'] = "Verbindung zum Socket fehlgeschlagen."; //copied from de-de
$text['message-connection']['de-ch'] = "Verbindung zum Socket fehlgeschlagen."; //copied from de-de
$text['message-connection']['de-de'] = "Verbindung zum Socket fehlgeschlagen.";
$text['message-connection']['es-cl'] = "Conexión a Socket de o fallida.";
$text['message-connection']['es-mx'] = "Conexión a Socket de o fallida."; //copied from es-cl
$text['message-connection']['fr-ca'] = "Connexion au socket en echec."; //copied from fr-fr
$text['message-connection']['fr-fr'] = "Connexion au socket en echec.";
$text['message-connection']['he-il'] = "";
$text['message-connection']['it-it'] = "Connessione all' Socket fallita.";
$text['message-connection']['nl-nl'] = "Verbinding met Socket mislukt";
$text['message-connection']['pl-pl'] = "Połączenie do „Socket” nie powiodło się";
$text['message-connection']['pt-br'] = "";
$text['message-connection']['pt-pt'] = "Conexão à Socket falhou.";
$text['message-connection']['ro-ro'] = "";
$text['message-connection']['ru-ru'] = "Подключение к Socket неудачно.";
$text['message-connection']['sv-se'] = "Anslutning till Händelse misslyckades";
$text['message-connection']['uk-ua'] = "";

$text['label-message']['en-us'] = "Message";
$text['label-message']['en-gb'] = "Message";
$text['label-message']['ar-eg'] = "";
$text['label-message']['de-at'] = "Nachricht"; //copied from de-de
$text['label-message']['de-ch'] = "Nachricht"; //copied from de-de
$text['label-message']['de-de'] = "Nachricht";
$text['label-message']['es-cl'] = "Mensaje";
$text['label-message']['es-mx'] = "Mensaje"; //copied from es-cl
$text['label-message']['fr-ca'] = "Message"; //copied from fr-fr
$text['label-message']['fr-fr'] = "Message";
$text['label-message']['he-il'] = "";
$text['label-message']['it-it'] = "Messaggio";
$text['label-message']['nl-nl'] = "Boodschap";
$text['label-message']['pl-pl'] = "Wiadomość";
$text['label-message']['pt-br'] = "Mensagem"; //copied from pt-pt
$text['label-message']['pt-pt'] = "Mensagem";
$text['label-message']['ro-ro'] = "";
$text['label-message']['ru-ru'] = "Сообщение";
$text['label-message']['sv-se'] = "Meddelande";
$text['label-message']['uk-ua'] = "Повідомлення";

$text['label-jail']['en-us'] = "Category";
$text['label-jail']['en-gb'] = "Category";
$text['label-jail']['ar-eg'] = "Category";
$text['label-jail']['de-at'] = "Kategorie";
$text['label-jail']['de-ch'] = "Kategorie";
$text['label-jail']['de-de'] = "Kategorie";
$text['label-jail']['el-gr'] = "Category";
$text['label-jail']['es-cl'] = "Category";
$text['label-jail']['es-mx'] = "Category";
$text['label-jail']['fr-ca'] = "Category";
$text['label-jail']['fr-fr'] = "Category";
$text['label-jail']['he-il'] = "Category";
$text['label-jail']['it-it'] = "Category";
$text['label-jail']['nl-nl'] = "Category";
$text['label-jail']['pl-pl'] = "Category";
$text['label-jail']['pt-br'] = "Category";
$text['label-jail']['pt-pt'] = "Category";
$text['label-jail']['ro-ro'] = "Category";
$text['label-jail']['ru-ru'] = "Category";
$text['label-jail']['sv-se'] = "Category";
$text['label-jail']['uk-ua'] = "Category";


$text['label-ip-address']['en-us'] = "IP-Address";
$text['label-ip-address']['en-gb'] = "IP-Address";
$text['label-ip-address']['ar-eg'] = "IP-Address";
$text['label-ip-address']['de-at'] = "IP-Adresse";
$text['label-ip-address']['de-ch'] = "IP-Adresse";
$text['label-ip-address']['de-de'] = "IP-Adresse";
$text['label-ip-address']['el-gr'] = "IP-Address";
$text['label-ip-address']['es-cl'] = "IP-Address";
$text['label-ip-address']['es-mx'] = "IP-Address";
$text['label-ip-address']['fr-ca'] = "IP-Address";
$text['label-ip-address']['fr-fr'] = "IP-Address";
$text['label-ip-address']['he-il'] = "IP-Address";
$text['label-ip-address']['it-it'] = "IP-Address";
$text['label-ip-address']['nl-nl'] = "IP-Address";
$text['label-ip-address']['pl-pl'] = "IP-Address";
$text['label-ip-address']['pt-br'] = "IP-Address";
$text['label-ip-address']['pt-pt'] = "IP-Address";
$text['label-ip-address']['ro-ro'] = "IP-Address";
$text['label-ip-address']['ru-ru'] = "IP-Address";
$text['label-ip-address']['sv-se'] = "IP-Address";
$text['label-ip-address']['uk-ua'] = "IP-Address";

$text['label-action']['en-us'] = "Action";
$text['label-action']['en-gb'] = "Action";
$text['label-action']['ar-eg'] = "";
$text['label-action']['de-at'] = "Aktion"; //copied from de-de
$text['label-action']['de-ch'] = "Aktion"; //copied from de-de
$text['label-action']['de-de'] = "Aktion";
$text['label-action']['el-gr'] = "Ενέργεια";
$text['label-action']['es-cl'] = "Acción";
$text['label-action']['es-mx'] = "Acción"; //copied from es-cl
$text['label-action']['fr-ca'] = "Action"; //copied from fr-fr
$text['label-action']['fr-fr'] = "Action";
$text['label-action']['he-il'] = "פעולה";
$text['label-action']['it-it'] = "Azione";
$text['label-action']['nl-nl'] = "Actie";
$text['label-action']['pl-pl'] = "Operacja";
$text['label-action']['pt-br'] = "Ação";
$text['label-action']['pt-pt'] = "Acção";
$text['label-action']['ro-ro'] = "Acțiune";
$text['label-action']['ru-ru'] = "Действие";
$text['label-action']['sv-se'] = "Åtgärd";
$text['label-action']['uk-ua'] = "Дія";

$text['button-unban']['en-us'] = "Unban";
$text['button-unban']['en-gb'] = "Unban";
$text['button-unban']['ar-eg'] = "Unban";
$text['button-unban']['de-at'] = "Sperre aufheben";
$text['button-unban']['de-ch'] = "Sperre aufheben";
$text['button-unban']['de-de'] = "Sperre aufheben";
$text['button-unban']['el-gr'] = "Unban";
$text['button-unban']['es-cl'] = "Unban";
$text['button-unban']['es-mx'] = "Unban";
$text['button-unban']['fr-ca'] = "Unban";
$text['button-unban']['fr-fr'] = "Unban";
$text['button-unban']['he-il'] = "Unban";
$text['button-unban']['it-it'] = "Unban";
$text['button-unban']['nl-nl'] = "Unban";
$text['button-unban']['pl-pl'] = "Unban";
$text['button-unban']['pt-br'] = "Unban";
$text['button-unban']['pt-pt'] = "Unban";
$text['button-unban']['ro-ro'] = "Unban";
$text['button-unban']['ru-ru'] = "Unban";
$text['button-unban']['sv-se'] = "Unban";
$text['button-unban']['uk-ua'] = "Unban";

$text['button-ban']['en-us'] = "Ban";
$text['button-ban']['en-gb'] = "Ban";
$text['button-ban']['ar-eg'] = "Ban";
$text['button-ban']['de-at'] = "Sperre einrichten";
$text['button-ban']['de-ch'] = "Sperre einrichten";
$text['button-ban']['de-de'] = "Sperre einrichten";
$text['button-ban']['el-gr'] = "Ban";
$text['button-ban']['es-cl'] = "Ban";
$text['button-ban']['es-mx'] = "Ban";
$text['button-ban']['fr-ca'] = "Ban";
$text['button-ban']['fr-fr'] = "Ban";
$text['button-ban']['he-il'] = "Ban";
$text['button-ban']['it-it'] = "Ban";
$text['button-ban']['nl-nl'] = "Ban";
$text['button-ban']['pl-pl'] = "Ban";
$text['button-ban']['pt-br'] = "Ban";
$text['button-ban']['pt-pt'] = "Ban";
$text['button-ban']['ro-ro'] = "Ban";
$text['button-ban']['ru-ru'] = "Ban";
$text['button-ban']['sv-se'] = "Ban";
$text['button-ban']['uk-ua'] = "Ban";

?>
